
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 5m0s
  timeout: 1m0s
  url: https://hub.jupyter.org/helm-chart/
