name: Publish package to the Maven Central Repository
on:
  pull_request:
    types:
      - closed


jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: print variables
        run: |
          echo "::info CHECK DRUID_VERSION"
          echo $DRUID_VERSION
          echo $IMAGE_TAG
          echo "::info CHECK DRUID_VERSION"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          echo "::error DOCKER BUILD"
          docker build --build-arg="DRUID_VERSION=$DRUID_VERSION" -t iunera/druid:$IMAGE_TAG .
          docker push iunera/druid:$IMAGE_TAG

      - name: Inspect
        run: |
          docker image inspect iunera/druid:$IMAGE_TAG