name: Test build on branches

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"
    paths:
      - "docker/**"
      - ".github/workflows**"

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: extract_targetversion
        run: |
          echo "IMAGE_TAG=latest-dev" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          echo "::error DOCKER BUILD"
          cd docker/datascience-notebook
          docker build -t iunera/datascience-notebook:$IMAGE_TAG .
          docker push iunera/datascience-notebook:$IMAGE_TAG


      - name: Inspect
        run: |
          docker image inspect iunera/datascience-notebook:$IMAGE_TAG